# version: "2"

services:
  rabbitmq:
    container_name: ms-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - sia_net
    restart: always

  master-db:
    container_name: ms-master-db
    image: postgres:15
    environment:
      POSTGRES_DB: master_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sia_net
    restart: always

  master-service:
    container_name: ms-master-service
    build: ./master-service
    image: master-service:1.0
    depends_on:
      - rabbitmq
      - master-db
    volumes:
      - ./master-service:/app
    environment:
      - NAMEKO_CONFIG=/app/config.yml
      - JWT_SECRET_KEY=abl_soa_finalProject
    networks:
      - sia_net
    restart: always
  
  gateway:
    container_name: ms-gateway
    build: ./gateway
    ports:
      - "8003:8000"
    depends_on:
      - rabbitmq
      - master-service
    volumes:
      - ./gateway:/app
    environment:
      - JWT_SECRET_KEY=abl_soa_finalProject
    networks:
      - sia_net
    restart: always

volumes:
  pgdata:

networks:
  sia_net:
    name: sia_network
    external: true