# version: "2"

services:
  rabbitmq:
    container_name: ms-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - sia_net
    restart: always

  # Master
  master-db:
    container_name: ms-master-db
    image: postgres:15
    environment:
      POSTGRES_DB: master_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sia_net
    restart: always

  master-service:
    container_name: ms-master-service
    build: ./master-service
    image: master-service:1.0
    depends_on:
      - rabbitmq
      - master-db
    volumes:
      - ./master-service:/app
    environment:
      - NAMEKO_CONFIG=/app/config.yml
      - JWT_SECRET_KEY=abl_soa_finalProject
    networks:
      - sia_net
    restart: always

  # Penawaran Kelas
  penawaran-db:
    container_name: ms-penawaran-db
    image: postgres:15
    environment:
      POSTGRES_DB: penawaran_db
      POSTGRES_USER: penawaran_user
      POSTGRES_PASSWORD: penawaran_password
    ports:
      - "5433:5432"
    volumes:
      - penawaran_pgdata:/var/lib/postgresql/data
    networks:
      - sia_net
    restart: always

  penawaran-service:
    container_name: ms-penawaran-service
    build: ./penawaran_kelas_service
    depends_on:
      - rabbitmq
      - penawaran-db
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: guest
      RABBIT_PASS: guest
      DB_HOST: penawaran-db
      DB_USER: penawaran_user
      DB_PASS: penawaran_password
      DB_NAME: penawaran_db
      NAMEKO_CONFIG: /app/config.yml
      JWT_SECRET_KEY: abl_soa_finalProject
    command: sh -c "sleep 10 && python write_config.py && python create_tables.py && nameko run --config runtime_config.yaml penawaran_kelas.service"
    networks:
      - sia_net
    restart: always

  # Perwalian
  perwalian-db:
    container_name: ms-perwalian-db
    image: postgres:15
    environment:
      POSTGRES_DB: perwalian_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - perwalian_pgdata:/var/lib/postgresql/data
    networks:
      - sia_net
    restart: always
    
  perwalian-service:
    container_name: ms-perwalian-service
    build: ./perwalian-service
    depends_on:
      - rabbitmq
      - perwalian-db
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: guest
      RABBIT_PASS: guest
      DB_HOST: perwalian-db
      DB_USER: perwalian_user
      DB_PASS: perwalian_password
      DB_NAME: perwalian_db
      NAMEKO_CONFIG: /app/config.yml
      JWT_SECRET_KEY: abl_soa_finalProject
    networks:
      - sia_net
    restart: always
  
  gateway:
    container_name: ms-gateway
    build: ./gateway
    ports:
      - "8003:8000"
    depends_on:
      - rabbitmq
      - master-service
      - penawaran-service
      - perwalian-service
    volumes:
      - ./gateway:/app
    environment:
      - JWT_SECRET_KEY=abl_soa_finalProject
    networks:
      - sia_net
    restart: always

volumes:
  pgdata:
    external: true
    name: master-service_pgdata
  penawaran_pgdata:
  perwalian_pgdata:

networks:
  sia_net:
    name: sia_network
    external: true